    <!-- TU KOÑCZY SIÊ KOD SPECYFICZNY DLA DANEJ STRONY -->
    <br />
    <table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#CCCCCC">
        <tr>
            <td><div align="center">&copy; 2011
           Mad programming, Maarek Gerwel designs, Inc.</div></td>
        </tr>
    </table>
    <p align="center">
    <a href="http://validator.w3.org/check?uri=referer"><img
        src="http://www.w3.org/Icons/valid-xhtml10"
        alt="Valid XHTML 1.0 Transitional" height="31" width="88" /></a>
    </p>
</body>
</html>